from math import pi



# Weight Fractions #
HEAD_WEIGHT_FRACTION = 0.0826
TORSO_WEIGHT_FRACTION = 0.551
UPPER_ARM_WEIGHT_FRACTION = 0.0325
FOREARM_WEIGHT_FRACTION = 0.0187 + 0.0065  # Including hand
THIGH_WEIGHT_FRACTION = 0.105
LEG_WEIGHT_FRACTION = 0.0475
FOOT_WEIGHT_FRACTION = 0.0143

# Height Fractions #
HEAD_HEIGHT_FRACTION = 0.1075
TORSO_HEIGHT_FRACTION = 0.3
UPPER_ARM_HEIGHT_FRACTION = 0.172
FOREARM_HEIGHT_FRACTION = 0.157  # Not including hand
THIGH_HEIGHT_FRACTION = 0.232
LEG_HEIGHT_FRACTION = 0.247
FOOT_HEIGHT_FRACTION = 0.0425

# Joint Constraints #
ELBOW_MIN_ANGLE = 0
ELBOW_MAX_ANGLE = 3*pi/4
SHOULDER_MIN_ANGLE = -pi/2
SHOULDER_MAX_ANGLE = pi
HIP_MIN_ANGLE = 0
HIP_MAX_ANGLE = 3*pi/4
KNEE_MIN_ANGLE = -2*pi/3
KNEE_MAX_ANGLE = 0
FOOT_MIN_ANGLE = -pi/4
FOOT_MAX_ANGLE = pi/4

